### NumPy First Steps

### Programming for Data Science
### Last Updated: Sep 22, 2025
---  

### PREREQUISITES
- import
- functions
- for ... in

### SOURCES 
- **Python for Data Analysis, Chapter 4 (be sure to read this)**
- https://numpy.org/
- https://en.wikipedia.org/wiki/NumPy
- https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html
- https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html

### OBJECTIVES
- Take your first steps with numpy
 


### CONCEPTS

- The numpy package contains useful functions for math operations
- The ndarray is the workhorse of the package


---

### numpy

In this lesson we will explore the python package *numpy*.  
This package is super powerful. 

Our focus will be on:
- importing and calling some random number generating functions
- illustrating operations on ndarrays
- learning how to subset ndarrays

### Motivation

I need a random number! I heard numpy can do that!  

In [1]:
import numpy as np
np.random.randint(1,7)

6

Learn what this function does:

In [2]:
help(np.random.randint)

Help on method randint in module numpy.random.mtrand:

randint(low, high=None, size=None, dtype=<class 'int'>) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)

    Return random integers from `low` (inclusive) to `high` (exclusive).

    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).

    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If prov

Include the size parameter to generate 10 random integers in [1, 6]

In [2]:
np.random.randint(1,7,10)

NameError: name 'np' is not defined

---

### The ndarray in Numpy

Details [here](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)

Represents a multidimensional, homogeneous array of fixed-size items. 

Uses very efficient operations

Arrays should be constructed using `array()`, `zeros()` or `empty()`.

### NumPy ndarray Operations


Create an array with some data

In [3]:
x = np.array(([2,3,1],[3,1,2]))
x

NameError: name 'np' is not defined

Get the shape of the data (rows, columns)

In [5]:
print(x.shape)

(2, 3)


In [7]:
# generate matrix of random normals 

x = np.random.randn(2, 3)
x

array([[-0.83074202,  0.38297382,  0.88910394],
       [-0.46450181,  0.92005621, -1.56537002]])

In [6]:
help(np.random.randn)

Help on method randn in module numpy.random.mtrand:

randn(*args) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)

    Return a sample (or samples) from the "standard normal" distribution.

    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.

    .. note::
        New code should use the
        `~numpy.random.Generator.standard_normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the dis

Scale the matrix - notice how this operates elementwise

In [8]:
x * 2

array([[-1.66148405,  0.76594764,  1.77820788],
       [-0.92900362,  1.84011242, -3.13074004]])

Addition

In [9]:
x + x

array([[-1.66148405,  0.76594764,  1.77820788],
       [-0.92900362,  1.84011242, -3.13074004]])

Reciprocal

In [10]:
1 / x

array([[-1.20374312,  2.61114456,  1.12472789],
       [-2.15284415,  1.08689011, -0.6388266 ]])

#### Creating Matrices with Special Structure - can create arrays of zeros, ones, and identity matrices

In [11]:
x=np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [19]:
x.shape

(5,)

In [20]:
y=np.zeros([5,1])

In [21]:
y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [22]:
y.shape

(5, 1)

In [23]:
z=np.zeros([1,5])
print(z)

[[0. 0. 0. 0. 0.]]


In [24]:
z.shape

(1, 5)

In [26]:
q=np.zeros((2,3))
print(q)

[[0. 0. 0.]
 [0. 0. 0.]]


In [27]:
q.shape

(2, 3)

In [28]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Indexing and Slicing

In [30]:
z = np.random.randn(5)
z

array([ 0.47468779, -0.12425421, -0.05308387,  0.94855445,  1.52760899])

In [31]:
# select from start to one before end
z[1:4]

array([-0.12425421, -0.05308387,  0.94855445])

In [32]:
# does this make sense?
z[1:-1]

array([-0.12425421, -0.05308387,  0.94855445])

In [33]:
# boolean indexing
z[z>0.15]

array([0.47468779, 0.94855445, 1.52760899])

In [37]:
z>0.15

array([ True,  True, False,  True,  True])

In [34]:
# assignment
z[1] = 3
z

array([ 0.47468779,  3.        , -0.05308387,  0.94855445,  1.52760899])

In [35]:
# 2D
w = np.random.randn(3,3)
w

array([[ 1.0000163 , -1.0101415 , -0.51654495],
       [-0.92159582, -0.66921574, -1.85507198],
       [ 0.80399407,  0.23338312,  0.30824369]])

In [36]:
# subset rows and columns
w[1:, :2]

array([[-0.92159582, -0.66921574],
       [ 0.80399407,  0.23338312]])

#### TRY FOR YOURSELF
Write code to generate a new array *w2* that starts with *w* and sets all negative values to 0.
Then print *w2* and *w*.  

Be sure to use:  
w2 = w.copy()  
or w will get updated as well

In [40]:
w2 = w.copy()
w2[w2 < 0] = 0
print('w2:\n', w2)
print('')
print('w:\n', w)

w2:
 [[1.0000163  0.         0.        ]
 [0.         0.         0.        ]
 [0.80399407 0.23338312 0.30824369]]

w:
 [[ 1.0000163  -1.0101415  -0.51654495]
 [-0.92159582 -0.66921574 -1.85507198]
 [ 0.80399407  0.23338312  0.30824369]]


---  

#### Next Steps

This notebook provided some information to get you started.

To learn more, please refer to your textbook and the links in the Sources section at top.